crowi:
    #image: bakudankun/crowi
    image: tukiyo3/crowi
    links:
        - db
        - redis
        - search
    ports:
        - 8100:3000

db:
    image: mongo

redis:
    image: redis:alpine

search:
    image: elasticsearch
    ports:
        - 9200:9200
        - 9300:9300
